### ISSUE TITLE
Exposed Credentials

### ISSUE THREAD

**Issue by samuel-108** [fuzztobread/scrapetweet#1]
Your credentials are exposed. Use environment variables. 

And add an .env.example file explaining how to structure the .env file. 

_If you are confused, you can ask Chat GPT._

Here is an reference:
https://medium.com/chingu/an-introduction-to-environment-variables-and-how-to-use-them-f602f66d15fa

Please move DB Credentials to .env file (Do not publish the dot env file). [Do rotate the credentials of already leaked accs]

And for cookies, specify in readme on how to gather them. Don't include such info on a repo, specially public ones. 

Here are some cyber sec posts, that'd help you get familiar with these. 

https://blog.netwrix.com/2022/11/14/how-to-hide-api-keys-github/

**Comment by fuzztobread** [comment]
Thank you for notifying me about the issue. It has been fixed and update has been done accordingly.
